### ISSUE TITLE
[Windows version] pulmonary vein clipping plate parallel to axial slices

### ISSUE THREAD

**Issue by k2031891** [CemrgAppDevelopers/CemrgApp#24]
### Prerequisites

Put an X between the brackets on the following lines if you have done all of the following:

* [X] Checked the wiki board for common solutions: <https://github.com/CemrgAppDevelopers/CemrgApp/wiki>
* [X] Checked that your issue isn't already filed: <https://github.com/search?q=+is%3Aissue+user%3ACemrgAppDevelopers>
* [X] Are you providing the log? <https://github.com/CemrgAppDevelopers/CemrgApp/wiki/Troubleshooting>

### Description

 When Display Clippers button is clicked, the displayed clipping plate seems to be parallel to axial slice image planes.

![image](https://user-images.githubusercontent.com/61836441/89659044-38b99780-d8c7-11ea-8c88-0e8d1529743f.png)

### Steps to Reproduce

1. Loading segmentation.
2. Loading segmentation.
3. Combine segmentation.
4. PV Clipper.
5. Unpick Flip Lines.
6. Find Centreliens.
7. Display Clippers.

**Expected behaviour:**

Clipping plate is expected to be perpendicular to the traced centre line.

**Actual behavior:**

Clipping plate seems to be parallel to axial slice image planes.

**Reproduces how often:**

All time.

### Additional Information

NVIDIA driver is updated to the latest version.
´´´

**Comment by alonsoJASL** [comment]
After running some tests, it seems to be a problem with the view renderer **in Windows**. The automatic clipper itself does the job even if the clippers look completely wrong. 

However, from a visual point of view, it's difficult to assess the clippers if they're not oriented correctly. 

the actual problem comes in the `CemrgAtriaClipper` module, probably in function `CalcParamsOfPlane(...)`. the normals are not being calculated or not being stored properly.

**Workarounds**
1. Use the manual (green) clippers (press the arrow keys when selecting a clipper).
2. trust the automatic (yellow) clippers and just carry on pressing the next button (again, the clippers are fine, they're just displayed weirdly).

**Tasks**
1. Perhaps provide the option to clip automatically (as in the scar plugin)

**Comment by k2031891** [comment]
For workarounds:
1. When pressing the arrow keys, the clipper disappears.
2. The automatic clippers do not work. Correct display of the clipper is important especially when the segmentation of veins are connected.

**Comment by alonsoJASL** [comment]
Pushed commit 4b5b14e with fix. Theproblem was on the CemrgAtriaClipper class.  For some reason, windows wasn't storing the correct values in the correct `x_s, y_s, z_s`  variables, so I changed it from: 
```c++
x_s = line->GetPoint(position+1)[0] - line->GetPoint(position)[0];
y_s = line->GetPoint(position+1)[1] - line->GetPoint(position)[1];
z_s = line->GetPoint(position+1)[2] - line->GetPoint(position)[2];
```
to
```c++
double pAtPos[3], pAtPosPP[3];
line->GetPoint(position+1, pAtPosPP);
line->GetPoint(position, pAtPos);
x_s = pAtPosPP[0] - pAtPos[0];
y_s = pAtPosPP[1] - pAtPos[1];
z_s = pAtPosPP[2] - pAtPos[2];
```
